name: CI

on:
  push:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - run: composer install --no-interaction --prefer-dist
      - run: composer run build-data
      - run: composer run check-data
      - run: composer run doctor
      - run: composer run analyse
      - run: composer test
      - run: git diff --exit-code
